coslr: true
endlr: 0.0
dataset:
  batch_size: 128
  dataset: cifar10
  dataroot: ./data/CIFAR10
  img_size: 32
  num_workers: 8
  use_gpu: true
networks:
  def_file: ./models/cifar/ResNet_Ensemble_Visulization.py
  params: {depth: 50, num_classes: 10}

model_dir: null
optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0001}

training_opt:
  log_dir: ./logs/classification/cifar10/ResNet_Ensemble_Visulization
  num_epochs: 100
  warmup_epoch: 5
  num_accmutations: 1
  milestone: [120, 160, 180]
  mixed_loss: true
  alpha: 0.4
  base_weight: 0.5
  gamma: 1
  g: 0.1
  mixer_type: mixup
