coslr: true
endlr: 0.0
dataset:
  batch_size: 128
  dataset: cifar10
  dataroot: ./data/CIFAR10
  img_size: 32
  num_workers: 8
  use_gpu: true
networks:
  def_file: ./models/ResNet_Ensemble.py
  params: {depth: 18, dropout: null, num_classes: 10, normalized: true, scale: 30}

model_dir: null
optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0001}

training_opt:
  log_dir: ./logs/cifar10/ResNet_Ensemble
  num_epochs: 200
  warmup_epoch: 5
  step1: 100
  step2: 150
  mixed_loss: true
  alpha: 0.8
  base_weight: 0.5
  gamma: 1
  mixer_type: mixup
