coslr: true
endlr: 0.0
dataset:
  batch_size: 64
  dataset: ImageNet
  dataroot: ./data/ImageNet
  img_size: 224
  num_workers: 8
  use_gpu: true
  autoaugment: true
networks:
  def_file: ./models/ResNet_Ensemble.py
  params: {depth: 50, num_classes: 1000}

model_dir: null
optim_params: {lr: 0.05, momentum: 0.9, weight_decay: 0.0001}

training_opt:
  log_dir: ./logs/classification/ImageNet/ResNet_Ensemble_200_epoch_autoaugment_
  num_epochs: 200
  warmup_epoch: 5
  num_accmutations: 1
  milestones: [120, 160, 180]
  base_weight: 0.5
  gamma: 1
  mixed_loss: true
  alpha: 0.2
  mixer_type: mixup
