coslr: true
endlr: 0.0
dataset:
  batch_size: 128
  dataset: cifar100
  dataroot: ./data/CIFAR100
  img_size: 32
  num_workers: 8
  use_gpu: true
  autoaugment: true
networks:
  def_file: ./models/cifar/PreActResNet_Ensemble.py
  params: {depth: 18, num_classes: 100}

model_dir: null
optim_params: {lr: 0.01, momentum: 0.9, weight_decay: 0.0001}

training_opt:
  log_dir: ./logs/classification/cifar100/PreActResNet_Ensemble
  num_epochs: 300
  warmup_epoch: 10
  num_accmutations: 1
  milestones: [120, 160, 180]
  mixed_loss: true
  alpha: 0.8
  base_weight: 0.5
  gamma: 1
  g: 0.1
  mixer_type: mixup
