coslr: true
endlr: 0.0
dataset:
  batch_size: 64
  dataset: cifar100
  dataroot: ./data/CIFAR100
  img_size: 224
  num_workers: 8
  use_gpu: true
networks:
  def_file: ./models/ResNet_Ensemble_DDP.py
  params: {depth: 18, num_classes: 100}

model_dir: null
optim_params: {lr: 0.05, momentum: 0.9, weight_decay: 0.0001}

training_opt:
  log_dir: ./logs/classification/cifar100/ResNet_Ensemble_no_aux
  num_epochs: 200
  warmup_epoch: 5
  num_accmutations: 1
  step1: 100
  step2: 150
  mixed_loss: true
  alpha: 0.2
  base_weight: 0.5
  gamma: 1
  mixer_type: mixup
