coslr: true
endlr: 0.0
dataset:
  batch_size: 32
  dataset: cifar100
  dataroot: ./data/CIFAR100
  img_size: 224
  num_workers: 8
  use_gpu: true
networks:
  def_file: ./models/ResNet_Ensemble.py
  params: {depth: 18, num_classes: 100, groups: 32, width_per_group: 4}

model_dir: null
optim_params: {lr: 0.05, momentum: 0.9, weight_decay: 0.0005}

training_opt:
  log_dir: ./logs/classification/cifar100/ResNeXt_Ensemble_224_
  num_epochs: 200
  warmup_epoch: 5
  num_accmutations: 1
  milestones: [120, 160, 180]
  mixed_loss: true
  alpha: 0.2
  base_weight: 0.5
  gamma: 1
  mixer_type: mixup
