coslr: true
endlr: 0.0
dataset:
  batch_size: 64
  dataset: cifar100
  dataroot: ./data/CIFAR100
  img_size: 32
  num_workers: 8
  use_gpu: true
networks:
  def_file: ./models/KD/cifar/vgg_ensemble.py
  params: {model_name: "vgg13_bn", num_classes: 100}


model_dir: null
optim_params: {lr: 0.05, momentum: 0.9, weight_decay: 0.0001}

training_opt:
  log_dir: ./logs/kd/cifar100/vgg13_ensemble_
  num_epochs: 100
  warmup_epoch: 5
  num_accmutations: 1
  milestones: [150, 180, 210] 
  mixed_loss: true
  alpha: 0.2
  mixer_type: mixup
  base_weight: 0.5
  gamma: 1
  g: 0.1
